* ergokv

A Rust library for easy integration with TiKV, providing derive macros for automatic CRUD operations.

[[https://crates.io/crates/ergokv][https://img.shields.io/crates/v/ergokv.svg]]
[[https://docs.rs/ergokv][https://docs.rs/ergokv/badge.svg]]
[[https://github.com/luciumagn/ergokv/blob/main/LICENSE][https://img.shields.io/badge/license-Fair-blue.svg]]

** Installation

Add this to your =Cargo.toml=:

#+BEGIN_SRC toml
[dependencies]
ergokv = { git = "https://github.com/luciumagn/ergokv" }
#+END_SRC

** Documentation

For detailed documentation, including usage examples and API reference, please visit:

[[https://docs.rs/ergokv][https://docs.rs/ergokv]]

You can also generate the documentation locally by running:

#+BEGIN_SRC bash
cargo doc --open
#+END_SRC

** Prerequisites

- Rust (edition 2021 or later)
- Protobuf
- GRPC
- TiKV (can be installed via TiUP)

** Usage

#+BEGIN_SRC rust
use ergokv::Store;
use serde::{Serialize, Deserialize};
use uuid::Uuid;

#[derive(Store, Serialize, Deserialize)]
struct User {
    #[key]
    id: Uuid,
    #[index]
    username: String,
    email: String,
}

// Now you can use methods like User::load(), User::save(), User::delete(), User::by_username()
#+END_SRC

** Testing

To run tests, ensure you have TiUP installed and then use:

#+BEGIN_SRC bash
cargo test
#+END_SRC

Tests will automatically start and stop a TiKV instance using TiUP.

I will be honest with you, chief, I made one test and that's it.

** License

This project is licensed under the Fair License:

#+BEGIN_QUOTE
Copyright (c) 2024 Lukáš Hozda

Usage of the works is permitted provided that this instrument is retained with the works, so that any entity that uses the works is notified of this instrument.

DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.
#+END_QUOTE

** Contributing

Contributions are welcome! Please feel free to submit a Pull Request.

There is a lot of things that could be improved:
- Make ergokv support more KV stores
- Improve documentation
- Allow swapping the serialization format (currently we use CBOR via ciborium)
- Let methods be generic (in the case of TiKV) over RawClient, Transaction and
  TransactionClient
- Add methods that retrieve multiple structures, to make it useful to e.g. fetch
  entities like articles and all users (note that this can be done already by manually making
  a sort of entity registry for yourself)

** GitHub Repository

[[https://github.com/luciumagn/ergokv][github.com/luciumagn/ergokv]]
